// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjL6T9OKOAHP3YxUNp-rvmIdCtWM-HEzk',
    appId: '1:34001039950:web:a6cfe308f4cf3ed239091f',
    messagingSenderId: '34001039950',
    projectId: 'flutter-chat-app-94209',
    authDomain: 'flutter-chat-app-94209.firebaseapp.com',
    storageBucket: 'flutter-chat-app-94209.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl7cpdUD0q1qiYgaZx-bNM43bmd9KWFH4',
    appId: '1:34001039950:android:dac92267fa0be1d939091f',
    messagingSenderId: '34001039950',
    projectId: 'flutter-chat-app-94209',
    storageBucket: 'flutter-chat-app-94209.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxgYKBDCPKODAvvfZUPNmcWyw-NZZ713A',
    appId: '1:34001039950:ios:efad43cd0d6a70c439091f',
    messagingSenderId: '34001039950',
    projectId: 'flutter-chat-app-94209',
    storageBucket: 'flutter-chat-app-94209.appspot.com',
    iosBundleId: 'com.example.chatBoxApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxgYKBDCPKODAvvfZUPNmcWyw-NZZ713A',
    appId: '1:34001039950:ios:efad43cd0d6a70c439091f',
    messagingSenderId: '34001039950',
    projectId: 'flutter-chat-app-94209',
    storageBucket: 'flutter-chat-app-94209.appspot.com',
    iosBundleId: 'com.example.chatBoxApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjL6T9OKOAHP3YxUNp-rvmIdCtWM-HEzk',
    appId: '1:34001039950:web:da0d7b46fa62abef39091f',
    messagingSenderId: '34001039950',
    projectId: 'flutter-chat-app-94209',
    authDomain: 'flutter-chat-app-94209.firebaseapp.com',
    storageBucket: 'flutter-chat-app-94209.appspot.com',
  );

}